# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.agent_settings import AgentSettings
from ..types.browser_settings import BrowserSettings
from ..types.proxy_settings import ProxySettings
from ..types.task_created_response import TaskCreatedResponse
from ..types.task_list_response import TaskListResponse
from ..types.task_log_file_response import TaskLogFileResponse
from ..types.task_status import TaskStatus
from ..types.task_update_action import TaskUpdateAction
from ..types.task_view import TaskView
from .raw_client import AsyncRawTasksClient, RawTasksClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TasksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTasksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTasksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTasksClient
        """
        return self._raw_client

    def list_tasks(
        self,
        *,
        page_size: typing.Optional[int] = None,
        page_number: typing.Optional[int] = None,
        session_id: typing.Optional[str] = None,
        filter_by: typing.Optional[TaskStatus] = None,
        after: typing.Optional[dt.datetime] = None,
        before: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TaskListResponse:
        """
        Get paginated list of AI agent tasks with optional filtering by session and status.

        Parameters
        ----------
        page_size : typing.Optional[int]

        page_number : typing.Optional[int]

        session_id : typing.Optional[str]

        filter_by : typing.Optional[TaskStatus]

        after : typing.Optional[dt.datetime]

        before : typing.Optional[dt.datetime]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskListResponse
            Successful Response

        Examples
        --------
        from browser_use import BrowserUse

        client = BrowserUse(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.tasks.list_tasks()
        """
        _response = self._raw_client.list_tasks(
            page_size=page_size,
            page_number=page_number,
            session_id=session_id,
            filter_by=filter_by,
            after=after,
            before=before,
            request_options=request_options,
        )
        return _response.data

    def create_task(
        self,
        *,
        task: str,
        system_prompt_extension: typing.Optional[str] = OMIT,
        session_id: typing.Optional[str] = OMIT,
        start_url: typing.Optional[str] = OMIT,
        max_agent_steps: typing.Optional[int] = OMIT,
        structured_output: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[str]]] = OMIT,
        secrets: typing.Optional[typing.Dict[str, typing.Optional[str]]] = OMIT,
        allowed_domains: typing.Optional[typing.Sequence[str]] = OMIT,
        persistence_profile_id: typing.Optional[str] = OMIT,
        agent: typing.Optional[AgentSettings] = OMIT,
        proxy: typing.Optional[ProxySettings] = OMIT,
        browser: typing.Optional[BrowserSettings] = OMIT,
        highlight_elements: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TaskCreatedResponse:
        """
        You can either:
        1. Start a new session with a new task (auto creates a new session)
        2. Add a follow-up task to an existing session (agent continues in the same browser session)

        Parameters
        ----------
        task : str

        system_prompt_extension : typing.Optional[str]

        session_id : typing.Optional[str]

        start_url : typing.Optional[str]

        max_agent_steps : typing.Optional[int]

        structured_output : typing.Optional[str]

        metadata : typing.Optional[typing.Dict[str, typing.Optional[str]]]

        secrets : typing.Optional[typing.Dict[str, typing.Optional[str]]]

        allowed_domains : typing.Optional[typing.Sequence[str]]

        persistence_profile_id : typing.Optional[str]

        agent : typing.Optional[AgentSettings]

        proxy : typing.Optional[ProxySettings]

        browser : typing.Optional[BrowserSettings]

        highlight_elements : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskCreatedResponse
            Successful Response

        Examples
        --------
        from browser_use import BrowserUse

        client = BrowserUse(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.tasks.create_task(
            task="task",
        )
        """
        _response = self._raw_client.create_task(
            task=task,
            system_prompt_extension=system_prompt_extension,
            session_id=session_id,
            start_url=start_url,
            max_agent_steps=max_agent_steps,
            structured_output=structured_output,
            metadata=metadata,
            secrets=secrets,
            allowed_domains=allowed_domains,
            persistence_profile_id=persistence_profile_id,
            agent=agent,
            proxy=proxy,
            browser=browser,
            highlight_elements=highlight_elements,
            request_options=request_options,
        )
        return _response.data

    def get_task(self, task_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TaskView:
        """
        Get detailed task information including status, progress, steps, and file outputs.

        Parameters
        ----------
        task_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskView
            Successful Response

        Examples
        --------
        from browser_use import BrowserUse

        client = BrowserUse(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.tasks.get_task(
            task_id="task_id",
        )
        """
        _response = self._raw_client.get_task(task_id, request_options=request_options)
        return _response.data

    def update_task(
        self, task_id: str, *, action: TaskUpdateAction, request_options: typing.Optional[RequestOptions] = None
    ) -> TaskView:
        """
        Control task execution with stop, pause, resume, or stop task and session actions.

        Parameters
        ----------
        task_id : str

        action : TaskUpdateAction

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskView
            Successful Response

        Examples
        --------
        from browser_use import BrowserUse

        client = BrowserUse(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.tasks.update_task(
            task_id="task_id",
            action="stop",
        )
        """
        _response = self._raw_client.update_task(task_id, action=action, request_options=request_options)
        return _response.data

    def get_task_logs(
        self, task_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> TaskLogFileResponse:
        """
        Get secure download URL for task execution logs with step-by-step details.

        Parameters
        ----------
        task_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskLogFileResponse
            Successful Response

        Examples
        --------
        from browser_use import BrowserUse

        client = BrowserUse(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.tasks.get_task_logs(
            task_id="task_id",
        )
        """
        _response = self._raw_client.get_task_logs(task_id, request_options=request_options)
        return _response.data


class AsyncTasksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTasksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTasksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTasksClient
        """
        return self._raw_client

    async def list_tasks(
        self,
        *,
        page_size: typing.Optional[int] = None,
        page_number: typing.Optional[int] = None,
        session_id: typing.Optional[str] = None,
        filter_by: typing.Optional[TaskStatus] = None,
        after: typing.Optional[dt.datetime] = None,
        before: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TaskListResponse:
        """
        Get paginated list of AI agent tasks with optional filtering by session and status.

        Parameters
        ----------
        page_size : typing.Optional[int]

        page_number : typing.Optional[int]

        session_id : typing.Optional[str]

        filter_by : typing.Optional[TaskStatus]

        after : typing.Optional[dt.datetime]

        before : typing.Optional[dt.datetime]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskListResponse
            Successful Response

        Examples
        --------
        import asyncio

        from browser_use import AsyncBrowserUse

        client = AsyncBrowserUse(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.tasks.list_tasks()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_tasks(
            page_size=page_size,
            page_number=page_number,
            session_id=session_id,
            filter_by=filter_by,
            after=after,
            before=before,
            request_options=request_options,
        )
        return _response.data

    async def create_task(
        self,
        *,
        task: str,
        system_prompt_extension: typing.Optional[str] = OMIT,
        session_id: typing.Optional[str] = OMIT,
        start_url: typing.Optional[str] = OMIT,
        max_agent_steps: typing.Optional[int] = OMIT,
        structured_output: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[str]]] = OMIT,
        secrets: typing.Optional[typing.Dict[str, typing.Optional[str]]] = OMIT,
        allowed_domains: typing.Optional[typing.Sequence[str]] = OMIT,
        persistence_profile_id: typing.Optional[str] = OMIT,
        agent: typing.Optional[AgentSettings] = OMIT,
        proxy: typing.Optional[ProxySettings] = OMIT,
        browser: typing.Optional[BrowserSettings] = OMIT,
        highlight_elements: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TaskCreatedResponse:
        """
        You can either:
        1. Start a new session with a new task (auto creates a new session)
        2. Add a follow-up task to an existing session (agent continues in the same browser session)

        Parameters
        ----------
        task : str

        system_prompt_extension : typing.Optional[str]

        session_id : typing.Optional[str]

        start_url : typing.Optional[str]

        max_agent_steps : typing.Optional[int]

        structured_output : typing.Optional[str]

        metadata : typing.Optional[typing.Dict[str, typing.Optional[str]]]

        secrets : typing.Optional[typing.Dict[str, typing.Optional[str]]]

        allowed_domains : typing.Optional[typing.Sequence[str]]

        persistence_profile_id : typing.Optional[str]

        agent : typing.Optional[AgentSettings]

        proxy : typing.Optional[ProxySettings]

        browser : typing.Optional[BrowserSettings]

        highlight_elements : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskCreatedResponse
            Successful Response

        Examples
        --------
        import asyncio

        from browser_use import AsyncBrowserUse

        client = AsyncBrowserUse(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.tasks.create_task(
                task="task",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_task(
            task=task,
            system_prompt_extension=system_prompt_extension,
            session_id=session_id,
            start_url=start_url,
            max_agent_steps=max_agent_steps,
            structured_output=structured_output,
            metadata=metadata,
            secrets=secrets,
            allowed_domains=allowed_domains,
            persistence_profile_id=persistence_profile_id,
            agent=agent,
            proxy=proxy,
            browser=browser,
            highlight_elements=highlight_elements,
            request_options=request_options,
        )
        return _response.data

    async def get_task(self, task_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TaskView:
        """
        Get detailed task information including status, progress, steps, and file outputs.

        Parameters
        ----------
        task_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskView
            Successful Response

        Examples
        --------
        import asyncio

        from browser_use import AsyncBrowserUse

        client = AsyncBrowserUse(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.tasks.get_task(
                task_id="task_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_task(task_id, request_options=request_options)
        return _response.data

    async def update_task(
        self, task_id: str, *, action: TaskUpdateAction, request_options: typing.Optional[RequestOptions] = None
    ) -> TaskView:
        """
        Control task execution with stop, pause, resume, or stop task and session actions.

        Parameters
        ----------
        task_id : str

        action : TaskUpdateAction

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskView
            Successful Response

        Examples
        --------
        import asyncio

        from browser_use import AsyncBrowserUse

        client = AsyncBrowserUse(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.tasks.update_task(
                task_id="task_id",
                action="stop",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_task(task_id, action=action, request_options=request_options)
        return _response.data

    async def get_task_logs(
        self, task_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> TaskLogFileResponse:
        """
        Get secure download URL for task execution logs with step-by-step details.

        Parameters
        ----------
        task_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskLogFileResponse
            Successful Response

        Examples
        --------
        import asyncio

        from browser_use import AsyncBrowserUse

        client = AsyncBrowserUse(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.tasks.get_task_logs(
                task_id="task_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_task_logs(task_id, request_options=request_options)
        return _response.data
