# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .proxy_country_code import ProxyCountryCode


class ProxySettings(UncheckedBaseModel):
    """
    Proxy configuration settings
    Attributes:
            enable: Whether proxy is enabled
            proxy_country_code: Country code for proxy location
    """

    enable: typing.Optional[bool] = None
    proxy_country_code: typing_extensions.Annotated[
        typing.Optional[ProxyCountryCode], FieldMetadata(alias="proxyCountryCode")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
