# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class TaskOutputFileResponse(UncheckedBaseModel):
    """
    Response model for output file requests

    Attributes:
            id: Unique identifier for the output file
            file_name: Name of the output file
        download_url: URL to download the output file
    """

    id: str
    file_name: typing_extensions.Annotated[str, FieldMetadata(alias="fileName")]
    download_url: typing_extensions.Annotated[str, FieldMetadata(alias="downloadUrl")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
