# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class TaskCreatedResponse(UncheckedBaseModel):
    """
    Response model for creating a task

    Attributes:
            id: Unique identifier for the created task
            session_id: The ID of the agent session this task belongs to
    """

    id: str
    session_id: typing_extensions.Annotated[str, FieldMetadata(alias="sessionId")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
