# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.account_view import AccountView
from .raw_client import AsyncRawAccountClient, RawAccountClient


class AccountClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAccountClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAccountClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAccountClient
        """
        return self._raw_client

    def get_account_me(self, *, request_options: typing.Optional[RequestOptions] = None) -> AccountView:
        """
        Get authenticated account information including credit balances and account details.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AccountView
            Successful Response

        Examples
        --------
        from browser_use import BrowserUse

        client = BrowserUse(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.account.get_account_me()
        """
        _response = self._raw_client.get_account_me(request_options=request_options)
        return _response.data


class AsyncAccountClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAccountClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAccountClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAccountClient
        """
        return self._raw_client

    async def get_account_me(self, *, request_options: typing.Optional[RequestOptions] = None) -> AccountView:
        """
        Get authenticated account information including credit balances and account details.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AccountView
            Successful Response

        Examples
        --------
        import asyncio

        from browser_use import AsyncBrowserUse

        client = AsyncBrowserUse(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.account.get_account_me()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_account_me(request_options=request_options)
        return _response.data
